# Generated by Django 4.1 on 2022-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue_venue_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_image',
            new_name='event_image',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='web',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='event_date',
            field=models.DateTimeField(null=True, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='venue',
            name='titre',
            field=models.CharField(max_length=120, null=True, verbose_name='event Name'),
        ),
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('sportif', 'sportif'), ('culturel', 'culturel')], max_length=200, null=True, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
