# Generated by Django 4.1 on 2022-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_venue_image_venue_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='titre',
            field=models.CharField(max_length=120, verbose_name='event Name'),
        ),
    ]
